//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteJavaCS.JavaServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://sw/", ConfigurationName="JavaServices.WSOperations")]
    public interface WSOperations {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/loginRequest", ReplyAction="http://sw/WSOperations/loginResponse")]
        ClienteJavaCS.JavaServices.loginResponse login(ClienteJavaCS.JavaServices.loginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/loginRequest", ReplyAction="http://sw/WSOperations/loginResponse")]
        System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.loginResponse> loginAsync(ClienteJavaCS.JavaServices.loginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento user del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/RegisterRequest", ReplyAction="http://sw/WSOperations/RegisterResponse")]
        ClienteJavaCS.JavaServices.RegisterResponse Register(ClienteJavaCS.JavaServices.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/RegisterRequest", ReplyAction="http://sw/WSOperations/RegisterResponse")]
        System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.RegisterResponse> RegisterAsync(ClienteJavaCS.JavaServices.RegisterRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/cargarClientesRequest", ReplyAction="http://sw/WSOperations/cargarClientesResponse")]
        void cargarClientes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/cargarClientesRequest", ReplyAction="http://sw/WSOperations/cargarClientesResponse")]
        System.Threading.Tasks.Task cargarClientesAsync();
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://sw/).
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/ProcesarPagoRequest", ReplyAction="http://sw/WSOperations/ProcesarPagoResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        ClienteJavaCS.JavaServices.ProcesarPagoResponse ProcesarPago(ClienteJavaCS.JavaServices.ProcesarPagoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://sw/WSOperations/ProcesarPagoRequest", ReplyAction="http://sw/WSOperations/ProcesarPagoResponse")]
        System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.ProcesarPagoResponse> ProcesarPagoAsync(ClienteJavaCS.JavaServices.ProcesarPagoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="login", Namespace="http://sw/", Order=0)]
        public ClienteJavaCS.JavaServices.loginRequestBody Body;
        
        public loginRequest() {
        }
        
        public loginRequest(ClienteJavaCS.JavaServices.loginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public loginRequestBody() {
        }
        
        public loginRequestBody(string user, string password) {
            this.user = user;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class loginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="loginResponse", Namespace="http://sw/", Order=0)]
        public ClienteJavaCS.JavaServices.loginResponseBody Body;
        
        public loginResponse() {
        }
        
        public loginResponse(ClienteJavaCS.JavaServices.loginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class loginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public loginResponseBody() {
        }
        
        public loginResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Register", Namespace="http://sw/", Order=0)]
        public ClienteJavaCS.JavaServices.RegisterRequestBody Body;
        
        public RegisterRequest() {
        }
        
        public RegisterRequest(ClienteJavaCS.JavaServices.RegisterRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegisterRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string user;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public double cash;
        
        public RegisterRequestBody() {
        }
        
        public RegisterRequestBody(string user, string password, double cash) {
            this.user = user;
            this.password = password;
            this.cash = cash;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RegisterResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RegisterResponse", Namespace="http://sw/", Order=0)]
        public ClienteJavaCS.JavaServices.RegisterResponseBody Body;
        
        public RegisterResponse() {
        }
        
        public RegisterResponse(ClienteJavaCS.JavaServices.RegisterResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class RegisterResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool @return;
        
        public RegisterResponseBody() {
        }
        
        public RegisterResponseBody(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPago", WrapperNamespace="http://sw/", IsWrapped=true)]
    public partial class ProcesarPagoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double pago;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public double total;
        
        public ProcesarPagoRequest() {
        }
        
        public ProcesarPagoRequest(double pago, double total) {
            this.pago = pago;
            this.total = total;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ProcesarPagoResponse", WrapperNamespace="http://sw/", IsWrapped=true)]
    public partial class ProcesarPagoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public double @return;
        
        public ProcesarPagoResponse() {
        }
        
        public ProcesarPagoResponse(double @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSOperationsChannel : ClienteJavaCS.JavaServices.WSOperations, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSOperationsClient : System.ServiceModel.ClientBase<ClienteJavaCS.JavaServices.WSOperations>, ClienteJavaCS.JavaServices.WSOperations {
        
        public WSOperationsClient() {
        }
        
        public WSOperationsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSOperationsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperationsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSOperationsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteJavaCS.JavaServices.loginResponse ClienteJavaCS.JavaServices.WSOperations.login(ClienteJavaCS.JavaServices.loginRequest request) {
            return base.Channel.login(request);
        }
        
        public bool login(string user, string password) {
            ClienteJavaCS.JavaServices.loginRequest inValue = new ClienteJavaCS.JavaServices.loginRequest();
            inValue.Body = new ClienteJavaCS.JavaServices.loginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            ClienteJavaCS.JavaServices.loginResponse retVal = ((ClienteJavaCS.JavaServices.WSOperations)(this)).login(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.loginResponse> ClienteJavaCS.JavaServices.WSOperations.loginAsync(ClienteJavaCS.JavaServices.loginRequest request) {
            return base.Channel.loginAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.loginResponse> loginAsync(string user, string password) {
            ClienteJavaCS.JavaServices.loginRequest inValue = new ClienteJavaCS.JavaServices.loginRequest();
            inValue.Body = new ClienteJavaCS.JavaServices.loginRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            return ((ClienteJavaCS.JavaServices.WSOperations)(this)).loginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteJavaCS.JavaServices.RegisterResponse ClienteJavaCS.JavaServices.WSOperations.Register(ClienteJavaCS.JavaServices.RegisterRequest request) {
            return base.Channel.Register(request);
        }
        
        public bool Register(string user, string password, double cash) {
            ClienteJavaCS.JavaServices.RegisterRequest inValue = new ClienteJavaCS.JavaServices.RegisterRequest();
            inValue.Body = new ClienteJavaCS.JavaServices.RegisterRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.cash = cash;
            ClienteJavaCS.JavaServices.RegisterResponse retVal = ((ClienteJavaCS.JavaServices.WSOperations)(this)).Register(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.RegisterResponse> ClienteJavaCS.JavaServices.WSOperations.RegisterAsync(ClienteJavaCS.JavaServices.RegisterRequest request) {
            return base.Channel.RegisterAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.RegisterResponse> RegisterAsync(string user, string password, double cash) {
            ClienteJavaCS.JavaServices.RegisterRequest inValue = new ClienteJavaCS.JavaServices.RegisterRequest();
            inValue.Body = new ClienteJavaCS.JavaServices.RegisterRequestBody();
            inValue.Body.user = user;
            inValue.Body.password = password;
            inValue.Body.cash = cash;
            return ((ClienteJavaCS.JavaServices.WSOperations)(this)).RegisterAsync(inValue);
        }
        
        public void cargarClientes() {
            base.Channel.cargarClientes();
        }
        
        public System.Threading.Tasks.Task cargarClientesAsync() {
            return base.Channel.cargarClientesAsync();
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ClienteJavaCS.JavaServices.ProcesarPagoResponse ClienteJavaCS.JavaServices.WSOperations.ProcesarPago(ClienteJavaCS.JavaServices.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPago(request);
        }
        
        public double ProcesarPago(double pago, double total) {
            ClienteJavaCS.JavaServices.ProcesarPagoRequest inValue = new ClienteJavaCS.JavaServices.ProcesarPagoRequest();
            inValue.pago = pago;
            inValue.total = total;
            ClienteJavaCS.JavaServices.ProcesarPagoResponse retVal = ((ClienteJavaCS.JavaServices.WSOperations)(this)).ProcesarPago(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.ProcesarPagoResponse> ClienteJavaCS.JavaServices.WSOperations.ProcesarPagoAsync(ClienteJavaCS.JavaServices.ProcesarPagoRequest request) {
            return base.Channel.ProcesarPagoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ClienteJavaCS.JavaServices.ProcesarPagoResponse> ProcesarPagoAsync(double pago, double total) {
            ClienteJavaCS.JavaServices.ProcesarPagoRequest inValue = new ClienteJavaCS.JavaServices.ProcesarPagoRequest();
            inValue.pago = pago;
            inValue.total = total;
            return ((ClienteJavaCS.JavaServices.WSOperations)(this)).ProcesarPagoAsync(inValue);
        }
    }
}
