//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClienteCS.CSService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CSService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPowNumber", ReplyAction="http://tempuri.org/IService1/GetPowNumberResponse")]
        string GetPowNumber(double value, int pow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetPowNumber", ReplyAction="http://tempuri.org/IService1/GetPowNumberResponse")]
        System.Threading.Tasks.Task<string> GetPowNumberAsync(double value, int pow);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLogin", ReplyAction="http://tempuri.org/IService1/GetLoginResponse")]
        bool GetLogin(string user, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetLogin", ReplyAction="http://tempuri.org/IService1/GetLoginResponse")]
        System.Threading.Tasks.Task<bool> GetLoginAsync(string user, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ClienteCS.CSService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ClienteCS.CSService.IService1>, ClienteCS.CSService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetPowNumber(double value, int pow) {
            return base.Channel.GetPowNumber(value, pow);
        }
        
        public System.Threading.Tasks.Task<string> GetPowNumberAsync(double value, int pow) {
            return base.Channel.GetPowNumberAsync(value, pow);
        }
        
        public bool GetLogin(string user, string password) {
            return base.Channel.GetLogin(user, password);
        }
        
        public System.Threading.Tasks.Task<bool> GetLoginAsync(string user, string password) {
            return base.Channel.GetLoginAsync(user, password);
        }
    }
}
